/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class', // or 'media'
  theme: {
    extend: {
      colors: {
        light: {
          primary: '#0A0A0A',
          background: '#F5F5F7',
          surface: '#FFFFFF',
          accent: '#2EB516',
          text: '#0A0A0A',
          textSecondary: '#6B7280',
          textTertiary: '#9ea5b0ff',
          border: '#E5E7EB',
          overlayLight: 'rgba(255, 255, 255, 0.8)',
          surfaceSecondary: '#F9FAFB',
          mutedGold: '#D4A017',
          deepNavy: '#1E3A8A',
          softBlush: '#FCE7E9',
          charcoal: '#374151',
          ivory: '#FAF9F6',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
          shadow: '#000000',
        },
        dark: {
          primary: '#FFFFFF',
          background: '#121212',
          surface: '#1E1E1E',
          accent: '#2EB516',
          text: '#E5E5E5',
          textSecondary: '#A1A1AA',
          textTertiary: '#babab5',
          border: '#2A2A2A',
          overlayLight: 'rgba(0, 0, 0, 0.8)',
          surfaceSecondary: '#2A2A2A',
          mutedGold: '#E6B84D',
          deepNavy: '#1E3A8A',
          softBlush: '#F4A7B0',
          charcoal: '#6B7280',
          ivory: '#E5E5E3',
          success: '#10B981',
          warning: '#F59E0B',
          error: '#EF4444',
          shadow: '#000000',
        },
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'h1': '32px',
        'h2': '24px',
        'h3': '20px',
        'body': '16px',
        'caption': '12px',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '40px',
      },
    },
  },
  plugins: [],
};